### PR TITLE
Fix 10.10 Yosemite Soundflowerbed Crash

### PR DESCRIPTION
**Pull request by antlauzon**
Fixes a crash in Soundflowerbed on 10.10 Yosemite.

### CODE REVIEW

**Comment by qdcarnicelli** [comment]
Anthony -

Ok, so I had some time to dig through all this. 

First off, readGlobalPrefs, writeGlobalPrefs, and related prefs functions certainly are a memory management mess. Lot of commented out CFReleases that are just leaking memory straight away. But small amounts memory, such that we can ignore that for now.

Looking at the original code though, the CFRelease(num) (line 1125) seems correct as it is. The CFPreferencesCopyAppValue() call creates the num, the if(num) ensures its not null, and then its released. Given that the crashlog is for a CFRelease(null), we can kind of rule out that that's the problem.

Guessing most likely the crashlog is something else stomping on memory, and the CFRelease(null) seen is an accident of that. I checked all the CFReleases in the codebase, and they are all well guarded with if(null) checks.

**Comment by anthonylauzon** [comment]
I don't understand the specific mechanics of the issue because I didn't try to hunt it down fully, however, this works and what's currently available doesn't.  If I have some extra time perhaps I'll follow up on the PR.

**Comment by anthonylauzon** [comment]
FYI this fix (or one strikingly similar to it) is starting to pop up in other forks.

**Comment by qdcarnicelli** [comment]
Got a link to the other ones? I'd like to look at them too.

**Comment by antlauzon** [comment]
https://github.com/mLupine/SoundflowerBed

Someone decided to take it upon themselves to create a whole fork around the patch.

**Pull request closed without merging**
